description: Builds a devFullRelease of ooni/probe-android.

pipeline:
  - action: setup-android
  - action: generate-android-keystore
  - action: build-android-dev-full-release
  - action: sign-android-apk
